package org.kie.kogito.saga.orchestrator.process;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Instance;
import javax.inject.Inject;
import javax.inject.Named;

import org.jbpm.process.core.datatype.impl.type.ObjectDataType;
import org.jbpm.ruleflow.core.RuleFlowProcessFactory;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.kogito.process.impl.AbstractProcess;
import org.kie.kogito.saga.orchestrator.app.Application;
import org.kie.kogito.saga.orchestrator.model.SagaModel;

@ApplicationScoped()
@Named("tripReservation")
public class TripReservationProcess extends AbstractProcess<SagaModel> {

    @Inject()
    Instance<WorkItemHandler> handlers;

    Application app;

    public TripReservationProcess() {
    }

    @Inject()
    public TripReservationProcess(Application app) {
        super(app.config().process());
        this.app = app;
    }

    public TripReservationProcessInstance createInstance(SagaModel value) {
        return new TripReservationProcessInstance(this, value, this.createProcessRuntime());
    }

    public TripReservationProcessInstance createInstance(String businessKey, SagaModel value) {
        return new TripReservationProcessInstance(this, value, businessKey, this.createProcessRuntime());
    }

    @Override
    public SagaModel createModel() {
        return new SagaModel();
    }

    @Override
    public TripReservationProcessInstance createInstance(org.kie.kogito.Model value) {
        return this.createInstance((SagaModel) value);
    }

    @Override
    public TripReservationProcessInstance createInstance(String businessKey, org.kie.kogito.Model value) {
        return this.createInstance(businessKey, (SagaModel) value);
    }

    @Override
    public TripReservationProcessInstance createInstance(org.kie.api.runtime.process.WorkflowProcessInstance wpi) {
        return new TripReservationProcessInstance(this, this.createModel(), this.createProcessRuntime(), wpi);
    }

    @Override
    public TripReservationProcessInstance createReadOnlyInstance(org.kie.api.runtime.process.WorkflowProcessInstance wpi) {
        return new TripReservationProcessInstance(this, this.createModel(), wpi);
    }

    @Override
    public TripReservationProcess configure() {
        super.configure();
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        return this;
    }

    protected void registerListeners() {
    }

    public org.kie.api.definition.process.Process process() {
        RuleFlowProcessFactory factory = RuleFlowProcessFactory.createProcess("tripReservation");
        factory.variable("sagaId", new ObjectDataType("java.lang.String"), "customTags", null);
        factory.variable("payload", new ObjectDataType("io.vertx.core.json.JsonObject"), "customTags", null);
        factory.variable("processInstanceId", new ObjectDataType("java.lang.String"), "customTags", null);
        factory.variable("event", new ObjectDataType("java.lang.String"), "customTags", null);
        factory.name("Trip Reservation Process");
        factory.packageName("org.kie.kogito.saga");
        factory.dynamic(false);
        factory.version("1.0");
        factory.visibility("Public");
        factory.metaData("Compensation", true);
        factory.metaData("TargetNamespace", "http://www.omg.org/bpmn20");
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode1 = factory.endNode(1);
        endNode1.name("Compensate");
        endNode1.terminate(false);
        endNode1.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode1.metaData("UniqueId", "_43E2145F-D921-4368-8D2F-39BF744DBA3D");
        endNode1.metaData("elementname", "Compensate");
        endNode1.metaData("Ref", "Compensate");
        endNode1.metaData("EventType", "signal");
        endNode1.metaData("x", 1891);
        endNode1.metaData("width", 56);
        endNode1.metaData("y", 778);
        endNode1.metaData("customScope", "processInstance");
        endNode1.metaData("height", 56);
        endNode1.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode2 = factory.eventNode(2);
        eventNode2.name("PaymentRequestFailed");
        eventNode2.eventType("Message-PaymentRequestFailed");
        eventNode2.variableName("event");
        eventNode2.metaData("UniqueId", "_316A5460-9FDB-4CC0-95CD-BF98698E5A7F");
        eventNode2.metaData("elementname", "PaymentRequestFailed");
        eventNode2.metaData("TriggerType", "ConsumeMessage");
        eventNode2.metaData("EventType", "message");
        eventNode2.metaData("x", 1716);
        eventNode2.metaData("width", 56);
        eventNode2.metaData("y", 740);
        eventNode2.metaData("TriggerRef", "PaymentRequestFailed");
        eventNode2.metaData("MessageType", "String");
        eventNode2.metaData("height", 56);
        eventNode2.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode3 = factory.endNode(3);
        endNode3.name("Compensate");
        endNode3.terminate(false);
        endNode3.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode3.metaData("UniqueId", "_33A0F800-5D55-4EEC-9CCF-579E2E0B5CC9");
        endNode3.metaData("elementname", "Compensate");
        endNode3.metaData("Ref", "Compensate");
        endNode3.metaData("EventType", "signal");
        endNode3.metaData("x", 1060);
        endNode3.metaData("width", 56);
        endNode3.metaData("y", 146);
        endNode3.metaData("height", 56);
        endNode3.done();
        org.jbpm.ruleflow.core.factory.TimerNodeFactory timerNode4 = factory.timerNode(4);
        timerNode4.name("Timeout");
        timerNode4.type(1);
        timerNode4.delay("PT1H");
        timerNode4.metaData("UniqueId", "_6476EAD6-3416-4146-AC49-3E17092F570A");
        timerNode4.metaData("EventType", "timer");
        timerNode4.metaData("x", 924);
        timerNode4.metaData("width", 56);
        timerNode4.metaData("y", 146);
        timerNode4.metaData("height", 56);
        timerNode4.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode5 = factory.eventNode(5);
        eventNode5.name("PaymentRequestSuccess");
        eventNode5.eventType("Message-PaymentRequestSuccess");
        eventNode5.variableName("event");
        eventNode5.metaData("UniqueId", "_69548561-C161-47DF-A995-37DA0BEDF9A2");
        eventNode5.metaData("elementname", "PaymentRequestSuccess");
        eventNode5.metaData("TriggerType", "ConsumeMessage");
        eventNode5.metaData("EventType", "message");
        eventNode5.metaData("x", 1716);
        eventNode5.metaData("width", 56);
        eventNode5.metaData("y", 548);
        eventNode5.metaData("TriggerRef", "PaymentRequestSuccess");
        eventNode5.metaData("MessageType", "String");
        eventNode5.metaData("height", 56);
        eventNode5.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode6 = factory.splitNode(6);
        splitNode6.name("Split");
        splitNode6.type(4);
        splitNode6.metaData("UniqueId", "_83F7FEAD-5758-4B12-A0BA-23B80243093A");
        splitNode6.metaData("EventBased", "true");
        splitNode6.metaData("x", 1580);
        splitNode6.metaData("width", 56);
        splitNode6.metaData("y", 548);
        splitNode6.metaData("height", 56);
        splitNode6.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode7 = factory.eventNode(7);
        eventNode7.name("FlightReservationFailed");
        eventNode7.eventType("Message-FlightReservationFailed");
        eventNode7.variableName("event");
        eventNode7.metaData("UniqueId", "_C859493A-2362-4EA1-9850-2971FAA9FBC9");
        eventNode7.metaData("elementname", "FlightReservationFailed");
        eventNode7.metaData("TriggerType", "ConsumeMessage");
        eventNode7.metaData("EventType", "message");
        eventNode7.metaData("x", 968);
        eventNode7.metaData("width", 56);
        eventNode7.metaData("y", 903);
        eventNode7.metaData("TriggerRef", "FlightReservationFailed");
        eventNode7.metaData("MessageType", "String");
        eventNode7.metaData("height", 56);
        eventNode7.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode8 = factory.eventNode(8);
        eventNode8.name("FlightReservationSuccess");
        eventNode8.eventType("Message-FlightReservationSuccess");
        eventNode8.variableName("event");
        eventNode8.metaData("UniqueId", "_45B580D2-4C0B-481D-B6E1-468A1A76DCF4");
        eventNode8.metaData("elementname", "FlightReservationSuccess");
        eventNode8.metaData("TriggerType", "ConsumeMessage");
        eventNode8.metaData("EventType", "message");
        eventNode8.metaData("x", 973);
        eventNode8.metaData("width", 56);
        eventNode8.metaData("y", 808);
        eventNode8.metaData("TriggerRef", "FlightReservationSuccess");
        eventNode8.metaData("MessageType", "String");
        eventNode8.metaData("height", 56);
        eventNode8.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode9 = factory.splitNode(9);
        splitNode9.name("Split");
        splitNode9.type(4);
        splitNode9.metaData("UniqueId", "_668B9171-1EC5-4752-9F3E-C9D68D94AFDB");
        splitNode9.metaData("EventBased", "true");
        splitNode9.metaData("x", 832);
        splitNode9.metaData("width", 56);
        splitNode9.metaData("y", 807);
        splitNode9.metaData("height", 56);
        splitNode9.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode10 = factory.eventNode(10);
        eventNode10.name("CarReservationFailed");
        eventNode10.eventType("Message-CarReservationFailed");
        eventNode10.variableName("event");
        eventNode10.metaData("UniqueId", "_F0A835B5-528D-47B9-8BFD-4C13A1D7EA3F");
        eventNode10.metaData("elementname", "CarReservationFailed");
        eventNode10.metaData("TriggerType", "ConsumeMessage");
        eventNode10.metaData("EventType", "message");
        eventNode10.metaData("x", 833);
        eventNode10.metaData("width", 56);
        eventNode10.metaData("y", 635);
        eventNode10.metaData("TriggerRef", "CarReservationFailed");
        eventNode10.metaData("MessageType", "String");
        eventNode10.metaData("height", 56);
        eventNode10.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode11 = factory.eventNode(11);
        eventNode11.name("CarReservationSuccess");
        eventNode11.eventType("Message-CarReservationSuccess");
        eventNode11.variableName("event");
        eventNode11.metaData("UniqueId", "_69D38ACF-C785-48E2-BD19-AB5E9C3CBA8D");
        eventNode11.metaData("elementname", "CarReservationSuccess");
        eventNode11.metaData("TriggerType", "ConsumeMessage");
        eventNode11.metaData("EventType", "message");
        eventNode11.metaData("x", 924);
        eventNode11.metaData("width", 56);
        eventNode11.metaData("y", 547);
        eventNode11.metaData("TriggerRef", "CarReservationSuccess");
        eventNode11.metaData("MessageType", "String");
        eventNode11.metaData("height", 56);
        eventNode11.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode12 = factory.splitNode(12);
        splitNode12.name("Split");
        splitNode12.type(4);
        splitNode12.metaData("UniqueId", "_E1929E42-3159-490E-BC14-765DA225925B");
        splitNode12.metaData("EventBased", "true");
        splitNode12.metaData("x", 711);
        splitNode12.metaData("width", 56);
        splitNode12.metaData("y", 548);
        splitNode12.metaData("height", 56);
        splitNode12.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode13 = factory.eventNode(13);
        eventNode13.name("HotelReservationSuccess");
        eventNode13.eventType("Message-HotelReservationSuccess");
        eventNode13.variableName("event");
        eventNode13.metaData("UniqueId", "_9005F385-EECA-4910-B813-3F7F26A159AC");
        eventNode13.metaData("elementname", "HotelReservationSuccess");
        eventNode13.metaData("TriggerType", "ConsumeMessage");
        eventNode13.metaData("EventType", "message");
        eventNode13.metaData("x", 833);
        eventNode13.metaData("width", 56);
        eventNode13.metaData("y", 440);
        eventNode13.metaData("TriggerRef", "HotelReservationSuccess");
        eventNode13.metaData("MessageType", "String");
        eventNode13.metaData("height", 56);
        eventNode13.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode14 = factory.eventNode(14);
        eventNode14.name("HotelReservationFailed");
        eventNode14.eventType("Message-HotelReservationFailed");
        eventNode14.variableName("event");
        eventNode14.metaData("UniqueId", "_B6654CFD-5156-42FE-9EE0-1194EB870CA1");
        eventNode14.metaData("elementname", "HotelReservationFailed");
        eventNode14.metaData("TriggerType", "ConsumeMessage");
        eventNode14.metaData("EventType", "message");
        eventNode14.metaData("x", 936);
        eventNode14.metaData("width", 56);
        eventNode14.metaData("y", 312);
        eventNode14.metaData("TriggerRef", "HotelReservationFailed");
        eventNode14.metaData("MessageType", "String");
        eventNode14.metaData("height", 56);
        eventNode14.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode15 = factory.splitNode(15);
        splitNode15.name("Split");
        splitNode15.type(4);
        splitNode15.metaData("UniqueId", "_6D0E46AE-3194-4DB0-8C71-BAF0FC116251");
        splitNode15.metaData("EventBased", "true");
        splitNode15.metaData("x", 833);
        splitNode15.metaData("width", 56);
        splitNode15.metaData("y", 312);
        splitNode15.metaData("height", 56);
        splitNode15.done();
        org.jbpm.ruleflow.core.factory.ActionNodeFactory actionNode16 = factory.actionNode(16);
        actionNode16.name("Set processInstanceId");
        actionNode16.action(kcontext -> {
            String processInstanceId = (String) kcontext.getVariable("processInstanceId");
            kcontext.setVariable("processInstanceId", kcontext.getProcessInstance().getId());
            ;
        });
        actionNode16.metaData("UniqueId", "_E9ADFB10-A6E3-406C-800F-B0868DCB2930");
        actionNode16.metaData("elementname", "Set processInstanceId");
        actionNode16.metaData("NodeType", "ScriptTask");
        actionNode16.metaData("x", 91);
        actionNode16.metaData("width", 154);
        actionNode16.metaData("y", 331);
        actionNode16.metaData("height", 102);
        actionNode16.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode17 = factory.endNode(17);
        endNode17.name("End");
        endNode17.terminate(false);
        endNode17.metaData("UniqueId", "_EE2D648F-9F13-45A3-960C-06996345712C");
        endNode17.metaData("x", 1711);
        endNode17.metaData("width", 56);
        endNode17.metaData("y", 331);
        endNode17.metaData("height", 56);
        endNode17.done();
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode18 = factory.workItemNode(18);
        workItemNode18.name("Trip Reservation Failed");
        workItemNode18.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendResponse_18_Handler");
        workItemNode18.workParameter("eventType", "TripReservationFailed");
        workItemNode18.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode18.workParameter("Operation", "sendResponse");
        workItemNode18.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode18.workParameter("operationImplementationRef", "sendResponse");
        workItemNode18.workParameter("implementation", "Java");
        workItemNode18.inMapping("processInstanceId", "processInstanceId");
        workItemNode18.inMapping("sagaId", "sagaId");
        workItemNode18.done();
        workItemNode18.metaData("UniqueId", "_E371CB0D-9233-4C1A-B877-5D8ADE2059A4");
        workItemNode18.metaData("Implementation", "Java");
        workItemNode18.metaData("elementname", "Trip Reservation Failed");
        workItemNode18.metaData("Type", "Service Task");
        workItemNode18.metaData("OperationRef", "_E371CB0D-9233-4C1A-B877-5D8ADE2059A4_ServiceOperation");
        workItemNode18.metaData("x", 1477);
        workItemNode18.metaData("width", 154);
        workItemNode18.metaData("y", 308);
        workItemNode18.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode19 = factory.endNode(19);
        endNode19.name("End");
        endNode19.terminate(false);
        endNode19.metaData("UniqueId", "_C3631638-BB67-4CEF-9E39-A22B7665C83F");
        endNode19.metaData("x", 2066);
        endNode19.metaData("width", 56);
        endNode19.metaData("y", 545);
        endNode19.metaData("height", 56);
        endNode19.done();
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode20 = factory.workItemNode(20);
        workItemNode20.name("Trip Reservation Success");
        workItemNode20.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendResponse_20_Handler");
        workItemNode20.workParameter("eventType", "TripReservationSuccess");
        workItemNode20.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode20.workParameter("Operation", "sendResponse");
        workItemNode20.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode20.workParameter("operationImplementationRef", "sendResponse");
        workItemNode20.workParameter("implementation", "Java");
        workItemNode20.inMapping("processInstanceId", "processInstanceId");
        workItemNode20.inMapping("sagaId", "sagaId");
        workItemNode20.done();
        workItemNode20.metaData("UniqueId", "_A026B085-0870-4512-A439-E5FA6C5DA682");
        workItemNode20.metaData("Implementation", "Java");
        workItemNode20.metaData("elementname", "Trip Reservation Success");
        workItemNode20.metaData("Type", "Service Task");
        workItemNode20.metaData("OperationRef", "_A026B085-0870-4512-A439-E5FA6C5DA682_ServiceOperation");
        workItemNode20.metaData("x", 1842);
        workItemNode20.metaData("width", 154);
        workItemNode20.metaData("y", 522);
        workItemNode20.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode21 = factory.workItemNode(21);
        workItemNode21.name("Cancel Flight Reservation");
        workItemNode21.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_21_Handler");
        workItemNode21.workParameter("eventType", "CancelFlightReservation");
        workItemNode21.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode21.workParameter("Operation", "sendCompensation");
        workItemNode21.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode21.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode21.workParameter("implementation", "Java");
        workItemNode21.inMapping("processInstanceId", "processInstanceId");
        workItemNode21.done();
        workItemNode21.metaData("UniqueId", "_7535C673-B784-4049-8BA9-2457672976AD");
        workItemNode21.metaData("Implementation", "Java");
        workItemNode21.metaData("elementname", "Cancel Flight Reservation");
        workItemNode21.metaData("Type", "Service Task");
        workItemNode21.metaData("isForCompensation", true);
        workItemNode21.metaData("OperationRef", "_7535C673-B784-4049-8BA9-2457672976AD_ServiceOperation");
        workItemNode21.metaData("x", 581);
        workItemNode21.metaData("width", 154);
        workItemNode21.metaData("y", 934);
        workItemNode21.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode22 = factory.workItemNode(22);
        workItemNode22.name("Cancel Car Reservation");
        workItemNode22.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_22_Handler");
        workItemNode22.workParameter("eventType", "CancelCarReservation");
        workItemNode22.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode22.workParameter("Operation", "sendCompensation");
        workItemNode22.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode22.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode22.workParameter("implementation", "Java");
        workItemNode22.inMapping("processInstanceId", "processInstanceId");
        workItemNode22.done();
        workItemNode22.metaData("UniqueId", "_F14D90E0-D379-4F33-BDEE-7484D403B225");
        workItemNode22.metaData("Implementation", "Java");
        workItemNode22.metaData("elementname", "Cancel Car Reservation");
        workItemNode22.metaData("Type", "Service Task");
        workItemNode22.metaData("isForCompensation", true);
        workItemNode22.metaData("OperationRef", "_F14D90E0-D379-4F33-BDEE-7484D403B225_ServiceOperation");
        workItemNode22.metaData("x", 578);
        workItemNode22.metaData("width", 154);
        workItemNode22.metaData("y", 657);
        workItemNode22.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode23 = factory.workItemNode(23);
        workItemNode23.name("Cancel Book Hotel");
        workItemNode23.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_23_Handler");
        workItemNode23.workParameter("eventType", "CancelHotelReservation");
        workItemNode23.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode23.workParameter("Operation", "sendCompensation");
        workItemNode23.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode23.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode23.workParameter("implementation", "Java");
        workItemNode23.inMapping("processInstanceId", "processInstanceId");
        workItemNode23.done();
        workItemNode23.metaData("UniqueId", "_2253AC2B-783E-43F3-94ED-326F09DD7D16");
        workItemNode23.metaData("Implementation", "Java");
        workItemNode23.metaData("elementname", "Cancel Book Hotel");
        workItemNode23.metaData("Type", "Service Task");
        workItemNode23.metaData("isForCompensation", true);
        workItemNode23.metaData("OperationRef", "_2253AC2B-783E-43F3-94ED-326F09DD7D16_ServiceOperation");
        workItemNode23.metaData("x", 581);
        workItemNode23.metaData("width", 154);
        workItemNode23.metaData("y", 420);
        workItemNode23.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode24 = factory.workItemNode(24);
        workItemNode24.name("Cancel Request Payment");
        workItemNode24.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_24_Handler");
        workItemNode24.workParameter("eventType", "CancelPaymentRequest");
        workItemNode24.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode24.workParameter("Operation", "sendCompensation");
        workItemNode24.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode24.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode24.workParameter("implementation", "Java");
        workItemNode24.inMapping("processInstanceId", "processInstanceId");
        workItemNode24.done();
        workItemNode24.metaData("UniqueId", "_4EE2789A-F3F9-4246-9028-073DF71AB390");
        workItemNode24.metaData("Implementation", "Java");
        workItemNode24.metaData("elementname", "Cancel Request Payment");
        workItemNode24.metaData("Type", "Service Task");
        workItemNode24.metaData("isForCompensation", true);
        workItemNode24.metaData("OperationRef", "_4EE2789A-F3F9-4246-9028-073DF71AB390_ServiceOperation");
        workItemNode24.metaData("x", 1346);
        workItemNode24.metaData("width", 154);
        workItemNode24.metaData("y", 683);
        workItemNode24.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.StartNodeFactory startNode25 = factory.startNode(25);
        startNode25.name("ReceiveCompensate");
        startNode25.interrupting(false);
        startNode25.metaData("UniqueId", "_71F471E9-B3CC-4B86-9A52-2BB6CAE40056");
        startNode25.metaData("elementname", "ReceiveCompensate");
        startNode25.metaData("TriggerType", "Signal");
        startNode25.metaData("x", 1210);
        startNode25.metaData("width", 56);
        startNode25.metaData("y", 330);
        startNode25.metaData("TriggerRef", "Compensate");
        startNode25.metaData("MessageType", "Compensate");
        startNode25.metaData("height", 56);
        startNode25.done();
        startNode25.trigger("Compensate", "");
        org.jbpm.ruleflow.core.factory.ActionNodeFactory actionNode26 = factory.actionNode(26);
        actionNode26.name("Compensate all");
        actionNode26.action(kcontext -> kcontext.getProcessInstance().signalEvent("Compensation", "tripReservation"));
        actionNode26.metaData("UniqueId", "_B839F1A9-A9F3-40DE-B902-F82579B43115");
        actionNode26.metaData("elementname", "Compensate all");
        actionNode26.metaData("NodeType", "IntermediateThrowEvent-None");
        actionNode26.metaData("x", 1341);
        actionNode26.metaData("width", 56);
        actionNode26.metaData("y", 331);
        actionNode26.metaData("height", 56);
        actionNode26.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode27 = factory.endNode(27);
        endNode27.name("Compensate");
        endNode27.terminate(false);
        endNode27.action(kcontext -> kcontext.getProcessInstance().signalEvent("Compensate", null));
        endNode27.metaData("UniqueId", "_CFBE8E05-08E6-4C98-9E09-B3F09E7CFE7C");
        endNode27.metaData("elementname", "Compensate");
        endNode27.metaData("Ref", "Compensate");
        endNode27.metaData("EventType", "signal");
        endNode27.metaData("x", 1077);
        endNode27.metaData("width", 56);
        endNode27.metaData("y", 242);
        endNode27.metaData("customScope", "processInstance");
        endNode27.metaData("height", 56);
        endNode27.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode28 = factory.endNode(28);
        endNode28.name("Compensate");
        endNode28.terminate(false);
        endNode28.action(kcontext -> kcontext.getProcessInstance().signalEvent("Compensate", null));
        endNode28.metaData("UniqueId", "_5DDBD93B-67A1-4268-B890-FD2E80BC82D9");
        endNode28.metaData("elementname", "Compensate");
        endNode28.metaData("Ref", "Compensate");
        endNode28.metaData("EventType", "signal");
        endNode28.metaData("x", 834);
        endNode28.metaData("width", 56);
        endNode28.metaData("y", 712);
        endNode28.metaData("customScope", "processInstance");
        endNode28.metaData("height", 56);
        endNode28.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode29 = factory.endNode(29);
        endNode29.name("Compensate");
        endNode29.terminate(false);
        endNode29.action(kcontext -> kcontext.getProcessInstance().signalEvent("Compensate", null));
        endNode29.metaData("UniqueId", "_84B68BB5-9442-4946-96B3-E6A0E02AEA4F");
        endNode29.metaData("elementname", "Compensate");
        endNode29.metaData("Ref", "Compensate");
        endNode29.metaData("EventType", "signal");
        endNode29.metaData("x", 1107);
        endNode29.metaData("width", 56);
        endNode29.metaData("y", 902);
        endNode29.metaData("customScope", "processInstance");
        endNode29.metaData("height", 56);
        endNode29.done();
        org.jbpm.ruleflow.core.factory.JoinFactory joinNode30 = factory.joinNode(30);
        joinNode30.name("Join");
        joinNode30.type(1);
        joinNode30.metaData("UniqueId", "_D5B0E47C-3992-48CC-8E10-E8E8EA3D0876");
        joinNode30.metaData("x", 1039);
        joinNode30.metaData("width", 56);
        joinNode30.metaData("y", 548);
        joinNode30.metaData("height", 56);
        joinNode30.done();
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode31 = factory.workItemNode(31);
        workItemNode31.name("Request Flight Reservation");
        workItemNode31.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_31_Handler");
        workItemNode31.workParameter("eventType", "FlightReservationRequest");
        workItemNode31.workParameter("processInstanceId", "processInstanceId");
        workItemNode31.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode31.workParameter("Operation", "sendRequest");
        workItemNode31.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode31.workParameter("operationImplementationRef", "sendRequest");
        workItemNode31.workParameter("implementation", "Java");
        workItemNode31.inMapping("payload", "payload");
        workItemNode31.done();
        workItemNode31.metaData("UniqueId", "_10C26516-AFBD-44B1-8987-82518BD86689");
        workItemNode31.metaData("Implementation", "Java");
        workItemNode31.metaData("elementname", "Request Flight Reservation");
        workItemNode31.metaData("Type", "Service Task");
        workItemNode31.metaData("OperationRef", "_10C26516-AFBD-44B1-8987-82518BD86689_ServiceOperation");
        workItemNode31.metaData("x", 362);
        workItemNode31.metaData("width", 154);
        workItemNode31.metaData("y", 784);
        workItemNode31.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode32 = factory.workItemNode(32);
        workItemNode32.name("Request Payment");
        workItemNode32.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_32_Handler");
        workItemNode32.workParameter("eventType", "PaymentRequest");
        workItemNode32.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode32.workParameter("Operation", "sendRequest");
        workItemNode32.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode32.workParameter("operationImplementationRef", "sendRequest");
        workItemNode32.workParameter("implementation", "Java");
        workItemNode32.inMapping("processInstanceId", "processInstanceId");
        workItemNode32.inMapping("payload", "payload");
        workItemNode32.done();
        workItemNode32.metaData("UniqueId", "_8C6C58EF-9892-440F-AFB5-94225F3D9100");
        workItemNode32.metaData("Implementation", "Java");
        workItemNode32.metaData("elementname", "Request Payment");
        workItemNode32.metaData("Type", "Service Task");
        workItemNode32.metaData("OperationRef", "_8C6C58EF-9892-440F-AFB5-94225F3D9100_ServiceOperation");
        workItemNode32.metaData("x", 1138);
        workItemNode32.metaData("width", 154);
        workItemNode32.metaData("y", 525);
        workItemNode32.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode33 = factory.workItemNode(33);
        workItemNode33.name("Request Car Reservation");
        workItemNode33.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_33_Handler");
        workItemNode33.workParameter("eventType", "CarReservationRequest");
        workItemNode33.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode33.workParameter("Operation", "sendRequest");
        workItemNode33.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode33.workParameter("operationImplementationRef", "sendRequest");
        workItemNode33.workParameter("implementation", "Java");
        workItemNode33.inMapping("processInstanceId", "processInstanceId");
        workItemNode33.inMapping("payload", "payload");
        workItemNode33.done();
        workItemNode33.metaData("UniqueId", "_42814385-DE17-4BBF-BDDF-53B473DF6C95");
        workItemNode33.metaData("Implementation", "Java");
        workItemNode33.metaData("elementname", "Request Car Reservation");
        workItemNode33.metaData("Type", "Service Task");
        workItemNode33.metaData("OperationRef", "_42814385-DE17-4BBF-BDDF-53B473DF6C95_ServiceOperation");
        workItemNode33.metaData("x", 362);
        workItemNode33.metaData("width", 154);
        workItemNode33.metaData("y", 525);
        workItemNode33.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode34 = factory.workItemNode(34);
        workItemNode34.name("Request Book Hotel");
        workItemNode34.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_34_Handler");
        workItemNode34.workParameter("eventType", "HotelReservationRequest");
        workItemNode34.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode34.workParameter("Operation", "sendRequest");
        workItemNode34.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode34.workParameter("operationImplementationRef", "sendRequest");
        workItemNode34.workParameter("implementation", "Java");
        workItemNode34.inMapping("processInstanceId", "processInstanceId");
        workItemNode34.inMapping("payload", "payload");
        workItemNode34.done();
        workItemNode34.metaData("UniqueId", "_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C");
        workItemNode34.metaData("Implementation", "Java");
        workItemNode34.metaData("elementname", "Request Book Hotel");
        workItemNode34.metaData("Type", "Service Task");
        workItemNode34.metaData("OperationRef", "_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C_ServiceOperation");
        workItemNode34.metaData("x", 362);
        workItemNode34.metaData("width", 154);
        workItemNode34.metaData("y", 294);
        workItemNode34.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode35 = factory.splitNode(35);
        splitNode35.name("Split");
        splitNode35.type(1);
        splitNode35.metaData("UniqueId", "_4B04E4AC-FF80-40E0-BDBF-980A9247C70D");
        splitNode35.metaData("x", 204);
        splitNode35.metaData("width", 56);
        splitNode35.metaData("y", 547);
        splitNode35.metaData("height", 56);
        splitNode35.done();
        org.jbpm.ruleflow.core.factory.StartNodeFactory startNode36 = factory.startNode(36);
        startNode36.name("Start");
        startNode36.interrupting(false);
        startNode36.metaData("UniqueId", "_B74E7A62-26A1-4988-90E9-990248E750EE");
        startNode36.metaData("x", 76);
        startNode36.metaData("width", 56);
        startNode36.metaData("y", 548);
        startNode36.metaData("height", 56);
        startNode36.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode37 = factory.boundaryEventNode(37);
        boundaryEventNode37.name("BoundaryEvent");
        boundaryEventNode37.eventType("Compensation");
        boundaryEventNode37.attachedTo("_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C");
        boundaryEventNode37.scope(null);
        boundaryEventNode37.metaData("UniqueId", "_58E981FC-65EF-46DB-9129-92BF1F1BE498");
        boundaryEventNode37.metaData("EventType", "compensation");
        boundaryEventNode37.metaData("x", 441);
        boundaryEventNode37.metaData("width", 56);
        boundaryEventNode37.metaData("y", 368);
        boundaryEventNode37.metaData("AttachedTo", "_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C");
        boundaryEventNode37.metaData("height", 56);
        boundaryEventNode37.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode38 = factory.boundaryEventNode(38);
        boundaryEventNode38.name("BoundaryEvent");
        boundaryEventNode38.eventType("Compensation");
        boundaryEventNode38.attachedTo("_42814385-DE17-4BBF-BDDF-53B473DF6C95");
        boundaryEventNode38.scope(null);
        boundaryEventNode38.metaData("UniqueId", "_F29E5E2C-BCD7-492B-B210-814690A92CED");
        boundaryEventNode38.metaData("EventType", "compensation");
        boundaryEventNode38.metaData("x", 440);
        boundaryEventNode38.metaData("width", 56);
        boundaryEventNode38.metaData("y", 599);
        boundaryEventNode38.metaData("AttachedTo", "_42814385-DE17-4BBF-BDDF-53B473DF6C95");
        boundaryEventNode38.metaData("height", 56);
        boundaryEventNode38.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode39 = factory.boundaryEventNode(39);
        boundaryEventNode39.name("BoundaryEvent");
        boundaryEventNode39.eventType("Compensation");
        boundaryEventNode39.attachedTo("_10C26516-AFBD-44B1-8987-82518BD86689");
        boundaryEventNode39.scope(null);
        boundaryEventNode39.metaData("UniqueId", "_6106C53C-B167-44EF-BBB2-FC5DCD6DCEED");
        boundaryEventNode39.metaData("EventType", "compensation");
        boundaryEventNode39.metaData("x", 443);
        boundaryEventNode39.metaData("width", 56);
        boundaryEventNode39.metaData("y", 858);
        boundaryEventNode39.metaData("AttachedTo", "_10C26516-AFBD-44B1-8987-82518BD86689");
        boundaryEventNode39.metaData("height", 56);
        boundaryEventNode39.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode40 = factory.boundaryEventNode(40);
        boundaryEventNode40.name("BoundaryEvent");
        boundaryEventNode40.eventType("Compensation");
        boundaryEventNode40.attachedTo("_8C6C58EF-9892-440F-AFB5-94225F3D9100");
        boundaryEventNode40.scope(null);
        boundaryEventNode40.metaData("UniqueId", "_A45D040B-E2AE-425C-8F95-A58BF2CCDCB1");
        boundaryEventNode40.metaData("EventType", "compensation");
        boundaryEventNode40.metaData("x", 1241);
        boundaryEventNode40.metaData("width", 56);
        boundaryEventNode40.metaData("y", 599);
        boundaryEventNode40.metaData("AttachedTo", "_8C6C58EF-9892-440F-AFB5-94225F3D9100");
        boundaryEventNode40.metaData("height", 56);
        boundaryEventNode40.done();
        factory.connection(2, 1, "_7C26F8F8-8B42-41B5-AA86-6A6D0654D2EA");
        factory.connection(6, 2, "_17477EAF-5EEB-4123-82FD-604D23B66506");
        factory.connection(4, 3, "_CC2D1F3D-8C18-46E1-A9E8-76664DD927BA");
        factory.connection(15, 4, "_647B82C2-DF28-4500-B56E-22178BDC9B02");
        factory.connection(6, 5, "_AE54ED87-A936-4EAD-BF05-7BFAF2815A48");
        factory.connection(32, 6, "_481C450D-8514-4656-9522-D6F5C9A99D67");
        factory.connection(9, 7, "_D128CF2A-ABD6-4765-950B-BA4EACD7F482");
        factory.connection(9, 8, "_5E698F32-022D-4C79-BB42-91EB0724123F");
        factory.connection(31, 9, "_81803181-F4EF-433F-9DD4-7880A291E8B8");
        factory.connection(12, 10, "_0E127B17-521E-4500-9E54-BDBD172983D7");
        factory.connection(12, 11, "_8B9ED87E-6442-4EEA-A4AB-DB03C792BD02");
        factory.connection(33, 12, "_42C55823-A8A7-45C0-881E-CC1D29D4E9D0");
        factory.connection(15, 13, "_E3DCDC26-6DE2-4030-BAB6-8E4143FF0D55");
        factory.connection(15, 14, "_EA71F36A-E04F-402E-A979-B50165329AFF");
        factory.connection(34, 15, "_EE61FC56-2793-48BF-8C43-A34F70A3054F");
        factory.connection(36, 16, "_84CD6AFA-86ED-4133-90F1-8EAE70669FD2");
        factory.connection(18, 17, "_B330E672-1DD6-4594-84B7-AA7404AFEBF6");
        factory.connection(26, 18, "_1F335899-C58A-44F0-9044-63FAA76B246A");
        factory.connection(20, 19, "_7057A17E-839E-40A5-B941-701BC5AF5D6F");
        factory.connection(5, 20, "_8C2D4C89-0662-4134-A435-E2DC80B9A1A8");
        factory.association(39, 21, "");
        factory.association(38, 22, "");
        factory.association(37, 23, "");
        factory.association(40, 24, "");
        factory.connection(25, 26, "_25E284B8-AE52-4F08-9BD0-7C8F16AC1A27");
        factory.connection(14, 27, "_C102AFED-FE80-464A-8CAB-155ADBF0BEB9");
        factory.connection(10, 28, "_B6A948B8-5B1C-4738-8590-9B8C3643208C");
        factory.connection(7, 29, "_2515BB55-E76B-4BBF-8421-CFF13739F4C7");
        factory.connection(8, 30, "_05B98FF5-D1CF-4BFD-B2EB-166192607319");
        factory.connection(11, 30, "_7B59C53A-27A4-4328-8B08-1764950FCA80");
        factory.connection(13, 30, "_0E329A34-CE45-4783-8C2F-EE0A979EB90E");
        factory.connection(35, 31, "_38B25510-78F4-41A4-8713-43E3C7CB7061");
        factory.connection(30, 32, "_AC4FC77E-906A-4097-B2FF-6DAE3B2A2D81");
        factory.connection(35, 33, "_FFB85155-D19A-4E1F-A22F-B1BD4A85ECEC");
        factory.connection(35, 34, "_5B8F0D10-DFBA-4715-AB9E-F9D7F5C091D5");
        factory.connection(16, 35, "_A0443888-0AA6-4929-87D8-A18262718930");
        factory.validate();
        return factory.getProcess();
    }

    public void init(@javax.enterprise.event.Observes() io.quarkus.runtime.StartupEvent event) {
        this.activate();
    }
}
