package org.kie.kogito.saga.orchestrator.process;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Instance;
import javax.inject.Inject;
import javax.inject.Named;

import org.jbpm.process.core.datatype.impl.type.ObjectDataType;
import org.jbpm.ruleflow.core.RuleFlowProcessFactory;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.kogito.process.impl.AbstractProcess;
import org.kie.kogito.saga.orchestrator.app.Application;
import org.kie.kogito.saga.orchestrator.model.SagaModel;

@ApplicationScoped()
@Named("tripReservation")
public class TripReservationProcess extends AbstractProcess<SagaModel> {

    @Inject()
    Instance<WorkItemHandler> handlers;

    Application app;

    public TripReservationProcess() {
    }

    @Inject()
    public TripReservationProcess(Application app) {
        super(app.config().process());
        this.app = app;
    }

    public TripReservationProcessInstance createInstance(SagaModel value) {
        return new TripReservationProcessInstance(this, value, this.createProcessRuntime());
    }

    public TripReservationProcessInstance createInstance(String businessKey, SagaModel value) {
        return new TripReservationProcessInstance(this, value, businessKey, this.createProcessRuntime());
    }

    @Override
    public SagaModel createModel() {
        return new SagaModel();
    }

    @Override
    public TripReservationProcessInstance createInstance(org.kie.kogito.Model value) {
        return this.createInstance((SagaModel) value);
    }

    @Override
    public TripReservationProcessInstance createInstance(String businessKey, org.kie.kogito.Model value) {
        return this.createInstance(businessKey, (SagaModel) value);
    }

    @Override
    public TripReservationProcessInstance createInstance(org.kie.api.runtime.process.WorkflowProcessInstance wpi) {
        return new TripReservationProcessInstance(this, this.createModel(), this.createProcessRuntime(), wpi);
    }

    @Override
    public TripReservationProcessInstance createReadOnlyInstance(org.kie.api.runtime.process.WorkflowProcessInstance wpi) {
        return new TripReservationProcessInstance(this, this.createModel(), wpi);
    }

    @Override
    public TripReservationProcess configure() {
        super.configure();
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        handlers.forEach(h -> services.getWorkItemManager().registerWorkItemHandler(h.getName(), h));
        return this;
    }

    protected void registerListeners() {
    }

    public org.kie.api.definition.process.Process process() {
        RuleFlowProcessFactory factory = RuleFlowProcessFactory.createProcess("tripReservation");
        factory.variable("sagaId", new ObjectDataType("java.lang.String"), "customTags", null);
        factory.variable("payload", new ObjectDataType("io.vertx.core.json.JsonObject"), "customTags", null);
        factory.variable("processInstanceId", new ObjectDataType("java.lang.String"), "customTags", null);
        factory.variable("event", new ObjectDataType("java.lang.String"), "customTags", null);
        factory.name("Trip Reservation Process");
        factory.packageName("org.kie.kogito.saga");
        factory.dynamic(true);
        factory.version("1.0");
        factory.visibility("Public");
        factory.metaData("Compensation", true);
        factory.metaData("TargetNamespace", "http://www.omg.org/bpmn20");
        org.jbpm.ruleflow.core.factory.ActionNodeFactory actionNode1 = factory.actionNode(1);
        actionNode1.name("pre-compensate");
        actionNode1.action(kcontext -> {
            System.out.println("Pre-compensate all");
            ;
        });
        actionNode1.metaData("UniqueId", "_260D1141-9276-4478-B5AD-F9767388DA93");
        actionNode1.metaData("elementname", "pre-compensate");
        actionNode1.metaData("NodeType", "ScriptTask");
        actionNode1.metaData("x", 1416);
        actionNode1.metaData("width", 154);
        actionNode1.metaData("y", 81);
        actionNode1.metaData("height", 102);
        actionNode1.done();
        org.jbpm.ruleflow.core.factory.MilestoneNodeFactory milestoneNode2 = factory.milestoneNode(2);
        milestoneNode2.name("Compensate");
        milestoneNode2.done();
        milestoneNode2.metaData("UniqueId", "_DE66289F-CB23-4A41-9F1A-481C16497963");
        milestoneNode2.metaData("elementname", "Compensate");
        milestoneNode2.metaData("x", 1184);
        milestoneNode2.metaData("width", 154);
        milestoneNode2.metaData("y", 81);
        milestoneNode2.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode3 = factory.endNode(3);
        endNode3.name("Compensate");
        endNode3.terminate(false);
        endNode3.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode3.metaData("UniqueId", "_43E2145F-D921-4368-8D2F-39BF744DBA3D");
        endNode3.metaData("elementname", "Compensate");
        endNode3.metaData("Ref", "Compensate");
        endNode3.metaData("EventType", "signal");
        endNode3.metaData("x", 1891);
        endNode3.metaData("width", 56);
        endNode3.metaData("y", 778);
        endNode3.metaData("customScope", "processInstance");
        endNode3.metaData("height", 56);
        endNode3.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode4 = factory.eventNode(4);
        eventNode4.name("PaymentRequestFailed");
        eventNode4.eventType("Message-PaymentRequestFailed");
        eventNode4.variableName("event");
        eventNode4.metaData("UniqueId", "_316A5460-9FDB-4CC0-95CD-BF98698E5A7F");
        eventNode4.metaData("elementname", "PaymentRequestFailed");
        eventNode4.metaData("TriggerType", "ConsumeMessage");
        eventNode4.metaData("EventType", "message");
        eventNode4.metaData("x", 1716);
        eventNode4.metaData("width", 56);
        eventNode4.metaData("y", 740);
        eventNode4.metaData("TriggerRef", "PaymentRequestFailed");
        eventNode4.metaData("MessageType", "String");
        eventNode4.metaData("height", 56);
        eventNode4.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode5 = factory.endNode(5);
        endNode5.name("Compensate");
        endNode5.terminate(false);
        endNode5.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode5.metaData("UniqueId", "_33A0F800-5D55-4EEC-9CCF-579E2E0B5CC9");
        endNode5.metaData("elementname", "Compensate");
        endNode5.metaData("Ref", "Compensate");
        endNode5.metaData("EventType", "signal");
        endNode5.metaData("x", 1060);
        endNode5.metaData("width", 56);
        endNode5.metaData("y", 146);
        endNode5.metaData("customScope", "processInstance");
        endNode5.metaData("height", 56);
        endNode5.done();
        org.jbpm.ruleflow.core.factory.TimerNodeFactory timerNode6 = factory.timerNode(6);
        timerNode6.name("Timeout");
        timerNode6.type(1);
        timerNode6.delay("PT1H");
        timerNode6.metaData("UniqueId", "_6476EAD6-3416-4146-AC49-3E17092F570A");
        timerNode6.metaData("EventType", "timer");
        timerNode6.metaData("x", 924);
        timerNode6.metaData("width", 56);
        timerNode6.metaData("y", 146);
        timerNode6.metaData("height", 56);
        timerNode6.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode7 = factory.eventNode(7);
        eventNode7.name("PaymentRequestSuccess");
        eventNode7.eventType("Message-PaymentRequestSuccess");
        eventNode7.variableName("event");
        eventNode7.metaData("UniqueId", "_69548561-C161-47DF-A995-37DA0BEDF9A2");
        eventNode7.metaData("elementname", "PaymentRequestSuccess");
        eventNode7.metaData("TriggerType", "ConsumeMessage");
        eventNode7.metaData("EventType", "message");
        eventNode7.metaData("x", 1716);
        eventNode7.metaData("width", 56);
        eventNode7.metaData("y", 548);
        eventNode7.metaData("TriggerRef", "PaymentRequestSuccess");
        eventNode7.metaData("MessageType", "String");
        eventNode7.metaData("height", 56);
        eventNode7.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode8 = factory.splitNode(8);
        splitNode8.name("Split");
        splitNode8.type(4);
        splitNode8.metaData("UniqueId", "_83F7FEAD-5758-4B12-A0BA-23B80243093A");
        splitNode8.metaData("EventBased", "true");
        splitNode8.metaData("x", 1580);
        splitNode8.metaData("width", 56);
        splitNode8.metaData("y", 548);
        splitNode8.metaData("height", 56);
        splitNode8.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode9 = factory.eventNode(9);
        eventNode9.name("FlightReservationFailed");
        eventNode9.eventType("Message-FlightReservationFailed");
        eventNode9.variableName("event");
        eventNode9.metaData("UniqueId", "_C859493A-2362-4EA1-9850-2971FAA9FBC9");
        eventNode9.metaData("elementname", "FlightReservationFailed");
        eventNode9.metaData("TriggerType", "ConsumeMessage");
        eventNode9.metaData("EventType", "message");
        eventNode9.metaData("x", 968);
        eventNode9.metaData("width", 56);
        eventNode9.metaData("y", 903);
        eventNode9.metaData("TriggerRef", "FlightReservationFailed");
        eventNode9.metaData("MessageType", "String");
        eventNode9.metaData("height", 56);
        eventNode9.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode10 = factory.eventNode(10);
        eventNode10.name("FlightReservationSuccess");
        eventNode10.eventType("Message-FlightReservationSuccess");
        eventNode10.variableName("event");
        eventNode10.metaData("UniqueId", "_45B580D2-4C0B-481D-B6E1-468A1A76DCF4");
        eventNode10.metaData("elementname", "FlightReservationSuccess");
        eventNode10.metaData("TriggerType", "ConsumeMessage");
        eventNode10.metaData("EventType", "message");
        eventNode10.metaData("x", 973);
        eventNode10.metaData("width", 56);
        eventNode10.metaData("y", 808);
        eventNode10.metaData("TriggerRef", "FlightReservationSuccess");
        eventNode10.metaData("MessageType", "String");
        eventNode10.metaData("height", 56);
        eventNode10.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode11 = factory.splitNode(11);
        splitNode11.name("Split");
        splitNode11.type(4);
        splitNode11.metaData("UniqueId", "_668B9171-1EC5-4752-9F3E-C9D68D94AFDB");
        splitNode11.metaData("EventBased", "true");
        splitNode11.metaData("x", 832);
        splitNode11.metaData("width", 56);
        splitNode11.metaData("y", 807);
        splitNode11.metaData("height", 56);
        splitNode11.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode12 = factory.eventNode(12);
        eventNode12.name("CarReservationFailed");
        eventNode12.eventType("Message-CarReservationFailed");
        eventNode12.variableName("event");
        eventNode12.metaData("UniqueId", "_F0A835B5-528D-47B9-8BFD-4C13A1D7EA3F");
        eventNode12.metaData("elementname", "CarReservationFailed");
        eventNode12.metaData("TriggerType", "ConsumeMessage");
        eventNode12.metaData("EventType", "message");
        eventNode12.metaData("x", 833);
        eventNode12.metaData("width", 56);
        eventNode12.metaData("y", 635);
        eventNode12.metaData("TriggerRef", "CarReservationFailed");
        eventNode12.metaData("MessageType", "String");
        eventNode12.metaData("height", 56);
        eventNode12.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode13 = factory.eventNode(13);
        eventNode13.name("CarReservationSuccess");
        eventNode13.eventType("Message-CarReservationSuccess");
        eventNode13.variableName("event");
        eventNode13.metaData("UniqueId", "_69D38ACF-C785-48E2-BD19-AB5E9C3CBA8D");
        eventNode13.metaData("elementname", "CarReservationSuccess");
        eventNode13.metaData("TriggerType", "ConsumeMessage");
        eventNode13.metaData("EventType", "message");
        eventNode13.metaData("x", 924);
        eventNode13.metaData("width", 56);
        eventNode13.metaData("y", 547);
        eventNode13.metaData("TriggerRef", "CarReservationSuccess");
        eventNode13.metaData("MessageType", "String");
        eventNode13.metaData("height", 56);
        eventNode13.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode14 = factory.splitNode(14);
        splitNode14.name("Split");
        splitNode14.type(4);
        splitNode14.metaData("UniqueId", "_E1929E42-3159-490E-BC14-765DA225925B");
        splitNode14.metaData("EventBased", "true");
        splitNode14.metaData("x", 711);
        splitNode14.metaData("width", 56);
        splitNode14.metaData("y", 548);
        splitNode14.metaData("height", 56);
        splitNode14.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode15 = factory.eventNode(15);
        eventNode15.name("HotelReservationSuccess");
        eventNode15.eventType("Message-HotelReservationSuccess");
        eventNode15.variableName("event");
        eventNode15.metaData("UniqueId", "_9005F385-EECA-4910-B813-3F7F26A159AC");
        eventNode15.metaData("elementname", "HotelReservationSuccess");
        eventNode15.metaData("TriggerType", "ConsumeMessage");
        eventNode15.metaData("EventType", "message");
        eventNode15.metaData("x", 833);
        eventNode15.metaData("width", 56);
        eventNode15.metaData("y", 440);
        eventNode15.metaData("TriggerRef", "HotelReservationSuccess");
        eventNode15.metaData("MessageType", "String");
        eventNode15.metaData("height", 56);
        eventNode15.done();
        org.jbpm.ruleflow.core.factory.EventNodeFactory eventNode16 = factory.eventNode(16);
        eventNode16.name("HotelReservationFailed");
        eventNode16.eventType("Message-HotelReservationFailed");
        eventNode16.variableName("event");
        eventNode16.metaData("UniqueId", "_B6654CFD-5156-42FE-9EE0-1194EB870CA1");
        eventNode16.metaData("elementname", "HotelReservationFailed");
        eventNode16.metaData("TriggerType", "ConsumeMessage");
        eventNode16.metaData("EventType", "message");
        eventNode16.metaData("x", 936);
        eventNode16.metaData("width", 56);
        eventNode16.metaData("y", 312);
        eventNode16.metaData("TriggerRef", "HotelReservationFailed");
        eventNode16.metaData("MessageType", "String");
        eventNode16.metaData("height", 56);
        eventNode16.done();
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode17 = factory.splitNode(17);
        splitNode17.name("Split");
        splitNode17.type(4);
        splitNode17.metaData("UniqueId", "_6D0E46AE-3194-4DB0-8C71-BAF0FC116251");
        splitNode17.metaData("EventBased", "true");
        splitNode17.metaData("x", 833);
        splitNode17.metaData("width", 56);
        splitNode17.metaData("y", 312);
        splitNode17.metaData("height", 56);
        splitNode17.done();
        org.jbpm.ruleflow.core.factory.ActionNodeFactory actionNode18 = factory.actionNode(18);
        actionNode18.name("Set processInstanceId");
        actionNode18.action(kcontext -> {
            java.lang.String processInstanceId = (java.lang.String) kcontext.getVariable("processInstanceId");
            kcontext.setVariable("processInstanceId", kcontext.getProcessInstance().getId());
            ;
        });
        actionNode18.metaData("UniqueId", "_E9ADFB10-A6E3-406C-800F-B0868DCB2930");
        actionNode18.metaData("elementname", "Set processInstanceId");
        actionNode18.metaData("NodeType", "ScriptTask");
        actionNode18.metaData("x", 77);
        actionNode18.metaData("width", 154);
        actionNode18.metaData("y", 633);
        actionNode18.metaData("height", 102);
        actionNode18.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode19 = factory.endNode(19);
        endNode19.name("End compensation");
        endNode19.terminate(true);
        endNode19.metaData("UniqueId", "_EE2D648F-9F13-45A3-960C-06996345712C");
        endNode19.metaData("elementname", "End compensation");
        endNode19.metaData("x", 1711);
        endNode19.metaData("width", 56);
        endNode19.metaData("y", 331);
        endNode19.metaData("height", 56);
        endNode19.done();
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode20 = factory.workItemNode(20);
        workItemNode20.name("Trip Reservation Failed");
        workItemNode20.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendResponse_20_Handler");
        workItemNode20.workParameter("eventType", "TripReservationFailed");
        workItemNode20.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode20.workParameter("Operation", "sendResponse");
        workItemNode20.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode20.workParameter("operationImplementationRef", "sendResponse");
        workItemNode20.workParameter("implementation", "Java");
        workItemNode20.inMapping("processInstanceId", "processInstanceId");
        workItemNode20.inMapping("sagaId", "sagaId");
        workItemNode20.done();
        workItemNode20.metaData("UniqueId", "_E371CB0D-9233-4C1A-B877-5D8ADE2059A4");
        workItemNode20.metaData("Implementation", "Java");
        workItemNode20.metaData("elementname", "Trip Reservation Failed");
        workItemNode20.metaData("Type", "Service Task");
        workItemNode20.metaData("OperationRef", "_E371CB0D-9233-4C1A-B877-5D8ADE2059A4_ServiceOperation");
        workItemNode20.metaData("x", 1477);
        workItemNode20.metaData("width", 154);
        workItemNode20.metaData("y", 308);
        workItemNode20.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode21 = factory.endNode(21);
        endNode21.name("End success");
        endNode21.terminate(true);
        endNode21.metaData("UniqueId", "_C3631638-BB67-4CEF-9E39-A22B7665C83F");
        endNode21.metaData("elementname", "End success");
        endNode21.metaData("x", 2066);
        endNode21.metaData("width", 56);
        endNode21.metaData("y", 545);
        endNode21.metaData("height", 56);
        endNode21.done();
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode22 = factory.workItemNode(22);
        workItemNode22.name("Trip Reservation Success");
        workItemNode22.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendResponse_22_Handler");
        workItemNode22.workParameter("eventType", "TripReservationSuccess");
        workItemNode22.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode22.workParameter("Operation", "sendResponse");
        workItemNode22.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode22.workParameter("operationImplementationRef", "sendResponse");
        workItemNode22.workParameter("implementation", "Java");
        workItemNode22.inMapping("processInstanceId", "processInstanceId");
        workItemNode22.inMapping("sagaId", "sagaId");
        workItemNode22.done();
        workItemNode22.metaData("UniqueId", "_A026B085-0870-4512-A439-E5FA6C5DA682");
        workItemNode22.metaData("Implementation", "Java");
        workItemNode22.metaData("elementname", "Trip Reservation Success");
        workItemNode22.metaData("Type", "Service Task");
        workItemNode22.metaData("OperationRef", "_A026B085-0870-4512-A439-E5FA6C5DA682_ServiceOperation");
        workItemNode22.metaData("x", 1842);
        workItemNode22.metaData("width", 154);
        workItemNode22.metaData("y", 522);
        workItemNode22.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode23 = factory.workItemNode(23);
        workItemNode23.name("Cancel Flight Reservation");
        workItemNode23.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_23_Handler");
        workItemNode23.workParameter("eventType", "CancelFlightReservation");
        workItemNode23.workParameter("compensateForType", "FlightReservationRequest");
        workItemNode23.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode23.workParameter("Operation", "sendCompensation");
        workItemNode23.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode23.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode23.workParameter("implementation", "Java");
        workItemNode23.inMapping("processInstanceId", "processInstanceId");
        workItemNode23.done();
        workItemNode23.metaData("UniqueId", "_7535C673-B784-4049-8BA9-2457672976AD");
        workItemNode23.metaData("Implementation", "Java");
        workItemNode23.metaData("elementname", "Cancel Flight Reservation");
        workItemNode23.metaData("Type", "Service Task");
        workItemNode23.metaData("isForCompensation", true);
        workItemNode23.metaData("OperationRef", "_7535C673-B784-4049-8BA9-2457672976AD_ServiceOperation");
        workItemNode23.metaData("x", 581);
        workItemNode23.metaData("width", 154);
        workItemNode23.metaData("y", 934);
        workItemNode23.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode24 = factory.workItemNode(24);
        workItemNode24.name("Cancel Car Reservation");
        workItemNode24.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_24_Handler");
        workItemNode24.workParameter("eventType", "CancelCarReservation");
        workItemNode24.workParameter("compensateForType", "CarReservationRequest");
        workItemNode24.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode24.workParameter("Operation", "sendCompensation");
        workItemNode24.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode24.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode24.workParameter("implementation", "Java");
        workItemNode24.inMapping("processInstanceId", "processInstanceId");
        workItemNode24.done();
        workItemNode24.metaData("UniqueId", "_F14D90E0-D379-4F33-BDEE-7484D403B225");
        workItemNode24.metaData("Implementation", "Java");
        workItemNode24.metaData("elementname", "Cancel Car Reservation");
        workItemNode24.metaData("Type", "Service Task");
        workItemNode24.metaData("isForCompensation", true);
        workItemNode24.metaData("OperationRef", "_F14D90E0-D379-4F33-BDEE-7484D403B225_ServiceOperation");
        workItemNode24.metaData("x", 578);
        workItemNode24.metaData("width", 154);
        workItemNode24.metaData("y", 657);
        workItemNode24.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode25 = factory.workItemNode(25);
        workItemNode25.name("Cancel Book Hotel");
        workItemNode25.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_25_Handler");
        workItemNode25.workParameter("eventType", "CancelHotelReservation");
        workItemNode25.workParameter("compensateForType", "HotelReservationRequest");
        workItemNode25.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode25.workParameter("Operation", "sendCompensation");
        workItemNode25.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode25.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode25.workParameter("implementation", "Java");
        workItemNode25.inMapping("processInstanceId", "processInstanceId");
        workItemNode25.done();
        workItemNode25.metaData("UniqueId", "_2253AC2B-783E-43F3-94ED-326F09DD7D16");
        workItemNode25.metaData("Implementation", "Java");
        workItemNode25.metaData("elementname", "Cancel Book Hotel");
        workItemNode25.metaData("Type", "Service Task");
        workItemNode25.metaData("isForCompensation", true);
        workItemNode25.metaData("OperationRef", "_2253AC2B-783E-43F3-94ED-326F09DD7D16_ServiceOperation");
        workItemNode25.metaData("x", 581);
        workItemNode25.metaData("width", 154);
        workItemNode25.metaData("y", 420);
        workItemNode25.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode26 = factory.workItemNode(26);
        workItemNode26.name("Cancel Request Payment");
        workItemNode26.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendCompensation_26_Handler");
        workItemNode26.workParameter("eventType", "CancelPaymentRequest");
        workItemNode26.workParameter("compensateForType", "PaymentRequest");
        workItemNode26.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode26.workParameter("Operation", "sendCompensation");
        workItemNode26.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode26.workParameter("operationImplementationRef", "sendCompensation");
        workItemNode26.workParameter("implementation", "Java");
        workItemNode26.inMapping("processInstanceId", "processInstanceId");
        workItemNode26.done();
        workItemNode26.metaData("UniqueId", "_4EE2789A-F3F9-4246-9028-073DF71AB390");
        workItemNode26.metaData("Implementation", "Java");
        workItemNode26.metaData("elementname", "Cancel Request Payment");
        workItemNode26.metaData("Type", "Service Task");
        workItemNode26.metaData("isForCompensation", true);
        workItemNode26.metaData("OperationRef", "_4EE2789A-F3F9-4246-9028-073DF71AB390_ServiceOperation");
        workItemNode26.metaData("x", 1346);
        workItemNode26.metaData("width", 154);
        workItemNode26.metaData("y", 683);
        workItemNode26.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.ActionNodeFactory actionNode27 = factory.actionNode(27);
        actionNode27.name("Compensate all");
        actionNode27.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensation", "tripReservation");
        });
        actionNode27.metaData("UniqueId", "_B839F1A9-A9F3-40DE-B902-F82579B43115");
        actionNode27.metaData("elementname", "Compensate all");
        actionNode27.metaData("NodeType", "IntermediateThrowEvent-None");
        actionNode27.metaData("x", 1341);
        actionNode27.metaData("width", 56);
        actionNode27.metaData("y", 331);
        actionNode27.metaData("height", 56);
        actionNode27.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode28 = factory.endNode(28);
        endNode28.name("Compensate");
        endNode28.terminate(false);
        endNode28.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode28.metaData("UniqueId", "_CFBE8E05-08E6-4C98-9E09-B3F09E7CFE7C");
        endNode28.metaData("elementname", "Compensate");
        endNode28.metaData("Ref", "Compensate");
        endNode28.metaData("EventType", "signal");
        endNode28.metaData("x", 1050);
        endNode28.metaData("width", 56);
        endNode28.metaData("y", 242);
        endNode28.metaData("customScope", "processInstance");
        endNode28.metaData("height", 56);
        endNode28.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode29 = factory.endNode(29);
        endNode29.name("Compensate");
        endNode29.terminate(false);
        endNode29.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode29.metaData("UniqueId", "_5DDBD93B-67A1-4268-B890-FD2E80BC82D9");
        endNode29.metaData("elementname", "Compensate");
        endNode29.metaData("Ref", "Compensate");
        endNode29.metaData("EventType", "signal");
        endNode29.metaData("x", 834);
        endNode29.metaData("width", 56);
        endNode29.metaData("y", 712);
        endNode29.metaData("customScope", "processInstance");
        endNode29.metaData("height", 56);
        endNode29.done();
        org.jbpm.ruleflow.core.factory.EndNodeFactory endNode30 = factory.endNode(30);
        endNode30.name("Compensate");
        endNode30.terminate(false);
        endNode30.action(kcontext -> {
            kcontext.getProcessInstance().signalEvent("Compensate", null);
        });
        endNode30.metaData("UniqueId", "_84B68BB5-9442-4946-96B3-E6A0E02AEA4F");
        endNode30.metaData("elementname", "Compensate");
        endNode30.metaData("Ref", "Compensate");
        endNode30.metaData("EventType", "signal");
        endNode30.metaData("x", 1107);
        endNode30.metaData("width", 56);
        endNode30.metaData("y", 902);
        endNode30.metaData("customScope", "processInstance");
        endNode30.metaData("height", 56);
        endNode30.done();
        org.jbpm.ruleflow.core.factory.JoinFactory joinNode31 = factory.joinNode(31);
        joinNode31.name("Join");
        joinNode31.type(1);
        joinNode31.metaData("UniqueId", "_D5B0E47C-3992-48CC-8E10-E8E8EA3D0876");
        joinNode31.metaData("x", 1039);
        joinNode31.metaData("width", 56);
        joinNode31.metaData("y", 548);
        joinNode31.metaData("height", 56);
        joinNode31.done();
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode32 = factory.workItemNode(32);
        workItemNode32.name("Request Flight Reservation");
        workItemNode32.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_32_Handler");
        workItemNode32.workParameter("eventType", "FlightReservationRequest");
        workItemNode32.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode32.workParameter("Operation", "sendRequest");
        workItemNode32.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode32.workParameter("operationImplementationRef", "sendRequest");
        workItemNode32.workParameter("implementation", "Java");
        workItemNode32.inMapping("processInstanceId", "processInstanceId");
        workItemNode32.inMapping("payload", "payload");
        workItemNode32.done();
        workItemNode32.metaData("UniqueId", "_10C26516-AFBD-44B1-8987-82518BD86689");
        workItemNode32.metaData("Implementation", "Java");
        workItemNode32.metaData("elementname", "Request Flight Reservation");
        workItemNode32.metaData("Type", "Service Task");
        workItemNode32.metaData("OperationRef", "_10C26516-AFBD-44B1-8987-82518BD86689_ServiceOperation");
        workItemNode32.metaData("x", 362);
        workItemNode32.metaData("width", 154);
        workItemNode32.metaData("y", 784);
        workItemNode32.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode33 = factory.workItemNode(33);
        workItemNode33.name("Request Payment");
        workItemNode33.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_33_Handler");
        workItemNode33.workParameter("eventType", "PaymentRequest");
        workItemNode33.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode33.workParameter("Operation", "sendRequest");
        workItemNode33.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode33.workParameter("operationImplementationRef", "sendRequest");
        workItemNode33.workParameter("implementation", "Java");
        workItemNode33.inMapping("processInstanceId", "processInstanceId");
        workItemNode33.inMapping("payload", "payload");
        workItemNode33.done();
        workItemNode33.metaData("UniqueId", "_8C6C58EF-9892-440F-AFB5-94225F3D9100");
        workItemNode33.metaData("Implementation", "Java");
        workItemNode33.metaData("elementname", "Request Payment");
        workItemNode33.metaData("Type", "Service Task");
        workItemNode33.metaData("OperationRef", "_8C6C58EF-9892-440F-AFB5-94225F3D9100_ServiceOperation");
        workItemNode33.metaData("x", 1138);
        workItemNode33.metaData("width", 154);
        workItemNode33.metaData("y", 525);
        workItemNode33.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode34 = factory.workItemNode(34);
        workItemNode34.name("Request Car Reservation");
        workItemNode34.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_34_Handler");
        workItemNode34.workParameter("eventType", "CarReservationRequest");
        workItemNode34.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode34.workParameter("Operation", "sendRequest");
        workItemNode34.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode34.workParameter("operationImplementationRef", "sendRequest");
        workItemNode34.workParameter("implementation", "Java");
        workItemNode34.inMapping("processInstanceId", "processInstanceId");
        workItemNode34.inMapping("payload", "payload");
        workItemNode34.done();
        workItemNode34.metaData("UniqueId", "_42814385-DE17-4BBF-BDDF-53B473DF6C95");
        workItemNode34.metaData("Implementation", "Java");
        workItemNode34.metaData("elementname", "Request Car Reservation");
        workItemNode34.metaData("Type", "Service Task");
        workItemNode34.metaData("OperationRef", "_42814385-DE17-4BBF-BDDF-53B473DF6C95_ServiceOperation");
        workItemNode34.metaData("x", 362);
        workItemNode34.metaData("width", 154);
        workItemNode34.metaData("y", 525);
        workItemNode34.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.WorkItemNodeFactory workItemNode35 = factory.workItemNode(35);
        workItemNode35.name("Request Book Hotel");
        workItemNode35.workName("org.kie.kogito.saga.orchestrator.EventEmitterService_sendRequest_35_Handler");
        workItemNode35.workParameter("eventType", "HotelReservationRequest");
        workItemNode35.workParameter("Interface", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode35.workParameter("Operation", "sendRequest");
        workItemNode35.workParameter("interfaceImplementationRef", "org.kie.kogito.saga.orchestrator.EventEmitterService");
        workItemNode35.workParameter("operationImplementationRef", "sendRequest");
        workItemNode35.workParameter("implementation", "Java");
        workItemNode35.inMapping("processInstanceId", "processInstanceId");
        workItemNode35.inMapping("payload", "payload");
        workItemNode35.done();
        workItemNode35.metaData("UniqueId", "_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C");
        workItemNode35.metaData("Implementation", "Java");
        workItemNode35.metaData("elementname", "Request Book Hotel");
        workItemNode35.metaData("Type", "Service Task");
        workItemNode35.metaData("OperationRef", "_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C_ServiceOperation");
        workItemNode35.metaData("x", 362);
        workItemNode35.metaData("width", 154);
        workItemNode35.metaData("y", 294);
        workItemNode35.metaData("height", 102);
        org.jbpm.ruleflow.core.factory.SplitFactory splitNode36 = factory.splitNode(36);
        splitNode36.name("Split");
        splitNode36.type(1);
        splitNode36.metaData("UniqueId", "_4B04E4AC-FF80-40E0-BDBF-980A9247C70D");
        splitNode36.metaData("x", 204);
        splitNode36.metaData("width", 56);
        splitNode36.metaData("y", 547);
        splitNode36.metaData("height", 56);
        splitNode36.done();
        org.jbpm.ruleflow.core.factory.StartNodeFactory startNode37 = factory.startNode(37);
        startNode37.name("Start");
        startNode37.interrupting(false);
        startNode37.metaData("UniqueId", "_B74E7A62-26A1-4988-90E9-990248E750EE");
        startNode37.metaData("x", 1);
        startNode37.metaData("width", 56);
        startNode37.metaData("y", 540);
        startNode37.metaData("height", 56);
        startNode37.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode38 = factory.boundaryEventNode(38);
        boundaryEventNode38.name("BoundaryEvent");
        boundaryEventNode38.eventType("Compensation");
        boundaryEventNode38.attachedTo("_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C");
        boundaryEventNode38.scope(null);
        boundaryEventNode38.metaData("UniqueId", "_58E981FC-65EF-46DB-9129-92BF1F1BE498");
        boundaryEventNode38.metaData("EventType", "compensation");
        boundaryEventNode38.metaData("x", 441);
        boundaryEventNode38.metaData("width", 56);
        boundaryEventNode38.metaData("y", 368);
        boundaryEventNode38.metaData("AttachedTo", "_7AC0AA3E-0F91-42A7-AED6-85662D09CA2C");
        boundaryEventNode38.metaData("height", 56);
        boundaryEventNode38.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode39 = factory.boundaryEventNode(39);
        boundaryEventNode39.name("BoundaryEvent");
        boundaryEventNode39.eventType("Compensation");
        boundaryEventNode39.attachedTo("_42814385-DE17-4BBF-BDDF-53B473DF6C95");
        boundaryEventNode39.scope(null);
        boundaryEventNode39.metaData("UniqueId", "_F29E5E2C-BCD7-492B-B210-814690A92CED");
        boundaryEventNode39.metaData("EventType", "compensation");
        boundaryEventNode39.metaData("x", 440);
        boundaryEventNode39.metaData("width", 56);
        boundaryEventNode39.metaData("y", 599);
        boundaryEventNode39.metaData("AttachedTo", "_42814385-DE17-4BBF-BDDF-53B473DF6C95");
        boundaryEventNode39.metaData("height", 56);
        boundaryEventNode39.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode40 = factory.boundaryEventNode(40);
        boundaryEventNode40.name("BoundaryEvent");
        boundaryEventNode40.eventType("Compensation");
        boundaryEventNode40.attachedTo("_10C26516-AFBD-44B1-8987-82518BD86689");
        boundaryEventNode40.scope(null);
        boundaryEventNode40.metaData("UniqueId", "_6106C53C-B167-44EF-BBB2-FC5DCD6DCEED");
        boundaryEventNode40.metaData("EventType", "compensation");
        boundaryEventNode40.metaData("x", 443);
        boundaryEventNode40.metaData("width", 56);
        boundaryEventNode40.metaData("y", 858);
        boundaryEventNode40.metaData("AttachedTo", "_10C26516-AFBD-44B1-8987-82518BD86689");
        boundaryEventNode40.metaData("height", 56);
        boundaryEventNode40.done();
        org.jbpm.ruleflow.core.factory.BoundaryEventNodeFactory boundaryEventNode41 = factory.boundaryEventNode(41);
        boundaryEventNode41.name("BoundaryEvent");
        boundaryEventNode41.eventType("Compensation");
        boundaryEventNode41.attachedTo("_8C6C58EF-9892-440F-AFB5-94225F3D9100");
        boundaryEventNode41.scope(null);
        boundaryEventNode41.metaData("UniqueId", "_A45D040B-E2AE-425C-8F95-A58BF2CCDCB1");
        boundaryEventNode41.metaData("EventType", "compensation");
        boundaryEventNode41.metaData("x", 1241);
        boundaryEventNode41.metaData("width", 56);
        boundaryEventNode41.metaData("y", 599);
        boundaryEventNode41.metaData("AttachedTo", "_8C6C58EF-9892-440F-AFB5-94225F3D9100");
        boundaryEventNode41.metaData("height", 56);
        boundaryEventNode41.done();
        factory.connection(2, 1, "_9A76BCA4-FE3F-49D1-8485-959F727CF1C3");
        factory.connection(4, 3, "_7C26F8F8-8B42-41B5-AA86-6A6D0654D2EA");
        factory.connection(8, 4, "_17477EAF-5EEB-4123-82FD-604D23B66506");
        factory.connection(6, 5, "_CC2D1F3D-8C18-46E1-A9E8-76664DD927BA");
        factory.connection(17, 6, "_647B82C2-DF28-4500-B56E-22178BDC9B02");
        factory.connection(8, 7, "_AE54ED87-A936-4EAD-BF05-7BFAF2815A48");
        factory.connection(33, 8, "_481C450D-8514-4656-9522-D6F5C9A99D67");
        factory.connection(11, 9, "_D128CF2A-ABD6-4765-950B-BA4EACD7F482");
        factory.connection(11, 10, "_5E698F32-022D-4C79-BB42-91EB0724123F");
        factory.connection(32, 11, "_81803181-F4EF-433F-9DD4-7880A291E8B8");
        factory.connection(14, 12, "_0E127B17-521E-4500-9E54-BDBD172983D7");
        factory.connection(14, 13, "_8B9ED87E-6442-4EEA-A4AB-DB03C792BD02");
        factory.connection(34, 14, "_42C55823-A8A7-45C0-881E-CC1D29D4E9D0");
        factory.connection(17, 15, "_E3DCDC26-6DE2-4030-BAB6-8E4143FF0D55");
        factory.connection(17, 16, "_EA71F36A-E04F-402E-A979-B50165329AFF");
        factory.connection(35, 17, "_EE61FC56-2793-48BF-8C43-A34F70A3054F");
        factory.connection(37, 18, "_84CD6AFA-86ED-4133-90F1-8EAE70669FD2");
        factory.connection(20, 19, "_B330E672-1DD6-4594-84B7-AA7404AFEBF6");
        factory.connection(27, 20, "_1F335899-C58A-44F0-9044-63FAA76B246A");
        factory.connection(22, 21, "_7057A17E-839E-40A5-B941-701BC5AF5D6F");
        factory.connection(7, 22, "_8C2D4C89-0662-4134-A435-E2DC80B9A1A8");
        factory.association(40, 23, "");
        factory.association(39, 24, "");
        factory.association(38, 25, "");
        factory.association(41, 26, "");
        factory.connection(1, 27, "_97831A2A-0CCB-4A26-A2B4-E0200C9CEF4A");
        factory.connection(16, 28, "_C102AFED-FE80-464A-8CAB-155ADBF0BEB9");
        factory.connection(12, 29, "_B6A948B8-5B1C-4738-8590-9B8C3643208C");
        factory.connection(9, 30, "_2515BB55-E76B-4BBF-8421-CFF13739F4C7");
        factory.connection(15, 31, "_0E329A34-CE45-4783-8C2F-EE0A979EB90E");
        factory.connection(13, 31, "_7B59C53A-27A4-4328-8B08-1764950FCA80");
        factory.connection(10, 31, "_05B98FF5-D1CF-4BFD-B2EB-166192607319");
        factory.connection(36, 32, "_38B25510-78F4-41A4-8713-43E3C7CB7061");
        factory.connection(31, 33, "_AC4FC77E-906A-4097-B2FF-6DAE3B2A2D81");
        factory.connection(36, 34, "_FFB85155-D19A-4E1F-A22F-B1BD4A85ECEC");
        factory.connection(36, 35, "_5B8F0D10-DFBA-4715-AB9E-F9D7F5C091D5");
        factory.connection(18, 36, "_A0443888-0AA6-4929-87D8-A18262718930");
        factory.validate();
        return factory.getProcess();
    }

    public void init(@javax.enterprise.event.Observes() io.quarkus.runtime.StartupEvent event) {
        this.activate();
    }
}
